# Makefile for building program
# Generated by tmake at 21:16, 2016/09/13
#     Project: program.pro
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -Wall -W -O2 
CXXFLAGS=	-std=c++11 -pipe -Wall -W -O2 
INCPATH	=	
LINK	=	g++
LFLAGS	=	
LIBS	=	$(SUBLIBS)  
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic
REMOVE	=	rm -f
TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	Bracket.hpp \
		Tag.hpp \
		TagParser.hpp
SOURCES =	Bracket.cpp \
		Tag.cpp \
		TagParser.cpp \
		main.cpp
OBJECTS =	Bracket.o \
		Tag.o \
		TagParser.o \
		main.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	program
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(REMOVE) $(TARGET) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake:
	tmake program.pro

dist:
	$(REMOVE) Makefile  *.kdevprj *.kdevses

clean:
	$(REMOVE) $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	$(REMOVE) core *~



####### Compile

Bracket.o: Bracket.cpp

Tag.o: Tag.cpp

TagParser.o: TagParser.cpp

gtest/test1.o: gtest/test1.cpp \
		Tag.hpp

main.o: main.cpp

